name: Primer workflow

on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hemlo world Actions!"

      - name: Bajar codigo
        uses: actions/checkout@v5

      - name: Probar c√≥digo
        run: python3 main.py

      - name: Crear imagen Docker
        run: docker build -t gcarmona/hemloworld .

      - name: Probar contenedor Docker
        run: docker run gcarmona/hemloworld
